# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BookmarkShareExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BookmarkShareExtension
    pod 'RealmSwift'
    pod 'SwiftLinkPreview'
end

target 'Switching' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Switching
    pod 'RealmSwift'
    pod 'SwiftLinkPreview'
end
